import type { Entity, Relation } from "../types";

const xsdType = (t: string): string =>
  ({
    UUID: "xsd:string",
    String: "xsd:string",
    Integer: "xsd:integer",
    Decimal: "xsd:decimal",
    Boolean: "xsd:boolean",
    DateTime: "xsd:dateTime",
    Text: "xsd:string",
    Enum: "xsd:string",
  }[t] || "xsd:string");

export function entitiesToTurtle(entities: Entity[], relations: Relation[]): string {
  const lines = [
    "@prefix owl: <http://www.w3.org/2002/07/owl#> .",
    "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
    "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
    "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
    "@prefix sh: <http://www.w3.org/ns/shacl#> .",
    "@prefix model: <https://model.enterprise.local/> .",
    "",
    "model: a owl:Ontology ;",
    `  rdfs:label "Enterprise Ontology" ;`,
    `  rdfs:comment "Generated by Ontology Workbench" .`,
    "",
  ];

  const metaclassMap: Record<string, string> = {
    Entity: "owl:Class",
    Relation: "owl:Class",
    Attribute: "owl:Class",
    ValueSet: "owl:Class",
  };

  for (const e of entities) {
    lines.push(`model:${e.name.replace(/\s/g, "")} a ${metaclassMap[e.metaclass] || "owl:Class"} ;`);
    lines.push(`  rdfs:label "${e.name}" ;`);
    lines.push(`  model:metaclass "${e.metaclass}" .`);
    lines.push("");
  }

  for (const e of entities) {
    for (const a of e.attributes) {
      const propName = `${e.name.replace(/\s/g, "")}/${a.name}`;
      lines.push(`model:${propName} a owl:DatatypeProperty ;`);
      lines.push(`  rdfs:domain model:${e.name.replace(/\s/g, "")} ;`);
      lines.push(`  rdfs:range ${xsdType(a.type)} ;`);
      if (a.pk) lines.push(`  model:primaryKey true ;`);
      lines.push(`  rdfs:label "${a.name}" .`);
      lines.push("");
    }
  }

  for (const r of relations) {
    const from = entities.find((e) => e.id === r.from);
    const to = entities.find((e) => e.id === r.to);
    if (!from || !to) continue;
    const propName = `${from.name.replace(/\s/g, "")}/${r.label.replace(/\s/g, "")}`;
    lines.push(`model:${propName} a owl:ObjectProperty ;`);
    lines.push(`  rdfs:domain model:${from.name.replace(/\s/g, "")} ;`);
    lines.push(`  rdfs:range model:${to.name.replace(/\s/g, "")} ;`);
    lines.push(`  rdfs:label "${r.label}" ;`);
    lines.push(`  model:cardinality "${r.card}" .`);
    lines.push("");
  }

  return lines.join("\n");
}

export function entitiesToShacl(entities: Entity[], relations: Relation[]): string {
  void relations;
  const lines = [
    "@prefix sh: <http://www.w3.org/ns/shacl#> .",
    "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
    "@prefix model: <https://model.enterprise.local/> .",
    "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
    "",
  ];

  for (const e of entities) {
    lines.push(`model:${e.name.replace(/\s/g, "")}Shape a sh:NodeShape ;`);
    lines.push(`  sh:targetClass model:${e.name.replace(/\s/g, "")} ;`);
    for (const a of e.attributes) {
      lines.push(`  sh:property [`);
      lines.push(`    sh:path model:${a.name} ;`);
      lines.push(`    sh:datatype ${xsdType(a.type)} ;`);
      if (a.pk || a.unique) lines.push(`    sh:minCount 1 ; sh:maxCount 1 ;`);
      else lines.push(`    sh:maxCount 1 ;`);
      lines.push(`  ] ;`);
    }
    lines.push(`.`);
    lines.push("");
  }

  return lines.join("\n");
}

export function entitiesToOwlJson(entities: Entity[], relations: Relation[]): string {
  return JSON.stringify(
    {
      "@context": {
        owl: "http://www.w3.org/2002/07/owl#",
        rdfs: "http://www.w3.org/2000/01/rdf-schema#",
        xsd: "http://www.w3.org/2001/XMLSchema#",
        model: "https://model.enterprise.local/",
      },
      "@graph": [
        { "@id": "model:", "@type": "owl:Ontology", "rdfs:label": "Enterprise Ontology" },
        ...entities.map((e) => ({
          "@id": `model:${e.name.replace(/\s/g, "")}`,
          "@type": "owl:Class",
          "rdfs:label": e.name,
          "model:metaclass": e.metaclass,
          "model:attributes": e.attributes.map((a) => ({ name: a.name, type: a.type, pk: !!a.pk })),
        })),
        ...relations
          .map((r) => {
            const from = entities.find((x) => x.id === r.from);
            const to = entities.find((x) => x.id === r.to);
            if (!from || !to) return null;
            return {
              "@id": `model:${from.name.replace(/\s/g, "")}/${r.label.replace(/\s/g, "")}`,
              "@type": "owl:ObjectProperty",
              "rdfs:domain": `model:${from.name.replace(/\s/g, "")}`,
              "rdfs:range": `model:${to.name.replace(/\s/g, "")}`,
              "rdfs:label": r.label,
            };
          })
          .filter(Boolean),
      ],
    },
    null,
    2
  );
}
